### ISSUE TITLE
Unnecessary cast

### ISSUE THREAD

**Issue by 4brunu** [kakai248/AutoViewModelFactory#1]
Hey, first of all, thanks for this amazing library!
I have one question/sugestion.
Why do you had this cast here? Is it necessary for some use case? 
https://github.com/kakai248/AutoViewModelFactory/blob/8903afd84ae2be2bde2c0493a9412a178bc7515c/processor/src/main/java/com/kakai/android/autoviewmodelfactory/processor/AutoViewModelFactoryProcessor.java#L172
Thanks 👍

**Comment by kakai248** [comment]
Hey, you're right, that cast is not really needed.

But I've found a better way of creating these factories. We can actually just make the factory a stub.

```kotlin
class ViewModelFactory<VM : ViewModel> @Inject constructor(private val viewModel: Lazy<VM>) : ViewModelProvider.Factory {

    @Suppress("UNCHECKED_CAST")
    override fun <T : ViewModel> create(modelClass: Class<T>): T {
        return viewModel.get() as T
    }
}
```

And then inject as usual:

```kotlin
@Inject
protected lateinit var viewModelFactory: ViewModelFactory<ViewModel>

lateinit var viewModel: ViewModel
    private set
```

```kotlin
viewModel = ViewModelProviders.of(this, viewModelFactory).get(viewModelClass())
```

You'll have everything created by dagger and not have another annotation processor slowing the build process.

**Comment by 4brunu** [comment]
Oh, cool, thanks for sharing! This is great. Initially I thought on trying something like this, but I was not sure if it would work. 👍

**Comment by ezamelczyk** [comment]
Hi @kakai248 

First of all, thanks for actually trying to address this issue, but I have a little problem with understanding how do inject these factories? I tried using your library but Dagger was giving me errors  because the auto generated factory wasn't annotated with my scope.

**Comment by kakai248** [comment]
@ezamelczyk Don't use the library. Just use the generic factory I pasted above.

And using this generic factory you don't need a scope (ie. you get a new instance every time). Combined with the `Lazy`, you will only create a new instance when it is actually needed. This works because we know when `ViewModelProviders` will actually call the factory `create`.

**Comment by matejdro** [comment]
Wow, I thought Dagger could not inject based on generics type alone. Thanks for this hint.

Could you add this to the README of the library, so everybody else does not need to dig through issues to find this?
