### ISSUE TITLE
Can you share your solution in detail?

### ISSUE THREAD

**Issue by dorukkangal** [kakai248/AutoViewModelFactory#4]
Hi Ricardo,

Thanks for this very useful library. I use this library because I have the same problem.
But when I checked it, I noticed that it was marked as deprecated because you found a better method. So I tried with lazy provider, but it didn't work.
I also reviewed [question](https://stackoverflow.com/q/46119375/1229664) and [comments](https://stackoverflow.com/a/48819177/1229664) on Stackoverflow but I haven't found the right method yet. Can you share your solution in detail?

Thank you.

**Comment by LDevi** [comment]
Hi @dorukkangal ,
I'm not using @kakai248 's great tool but I ended up with the same "ViewModelFactory" solution (with Dagger 2). 
It took me a while to figure what the issue was : I was using  **kotlin.Lazy** interface instead of, explicitly, **import dagger.Lazy**. Everything is fine now.

My two cents.

**Comment by kakai248** [comment]
Hi @dorukkangal, sorry for the delay.

Here's an example:

**ViewModelFactory.kt**
```kotlin
class ViewModelFactory<VM : ViewModel> @Inject constructor(private val viewModel: Lazy<VM>) : ViewModelProvider.Factory {
    @Suppress("UNCHECKED_CAST")
    override fun <T : ViewModel> create(modelClass: Class<T>): T {
        return viewModel.get() as T
    }
}
```

**BaseFragment.kt**
```kotlin
abstract class BaseFragment<VM : BaseViewModel> : DaggerFragment() {

    @Inject
    protected lateinit var viewModelFactory: ViewModelFactory<ViewModel>

    lateinit var viewModel: ViewModel
        private set

    override fun onActivityCreated(savedInstanceState: Bundle?) {
        super.onActivityCreated(savedInstanceState)
        viewModel = ViewModelProviders.of(this, viewModelFactory).get(viewModelClass())
    }

    protected abstract fun viewModelClass(): Class<VM>
}
```

**BaseViewModel.kt**
```kotlin
abstract class BaseViewModel : ViewModel()
```

**MainFragment.kt**
```kotlin
class MainFragment : BaseFragment<MainViewModel>() {
    override fun viewModelClass(): Class<MainViewModel> = MainViewModel::class.java
}
```

**MainViewModel.kt**
```kotlin
class MainViewModel @Inject constructor() : BaseViewModel()
```

And as @LDevi said, be careful with the `Lazy` as it needs to be the dagger one.

**Comment by smedegaard** [comment]
~~@kakai248 , `viewModel = ViewModelProviders.of(this, viewModelFactory).get(viewModelClass())` does not accept a `DaggerFragment`. Or did I mistype something?~~

nevermind, needs to be `import dagger.android.support.DaggerFragment`

**Comment by smedegaard** [comment]
Would I have to cast my instance of `viewModel` in my fragment?

It seems like I loose access to it's properties when I use the example code. I'm assuming it's because of `lateinit`
